{{- if .Values.ingressHttps.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-https
  namespace: {{ .Release.Namespace }}
  annotations:
    ingress.vke.volcengine.com/loadbalancer-protocol: https
    ingress.vke.volcengine.com/listener-port: "443"
spec:
  ingressClassName: {{ .Values.ingress.className | default "nginx" }}
  {{- if and .Values.ingress.host .Values.ingress.tlsSecret }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tlsSecret }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | default "" }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  number: 80
{{- end }}


