apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-app-https
  namespace: app-staging
  annotations:
    ingress.vke.volcengine.com/address-type: internet
    ingress.vke.volcengine.com/target-type: instance
    ingress.vke.volcengine.com/backend-protocol: HTTP
    ingress.vke.volcengine.com/alb-instance-id: alb-bdccywbfh0xs8dv40ord8u4k
    ingress.vke.volcengine.com/health-check-host: app-staging.chekkk.com
    ingress.vke.volcengine.com/health-check-path: /
    ingress.vke.volcengine.com/success-codes: "200,301,302"
    ingress.vke.volcengine.com/loadbalancer-port: "443"
    ingress.vke.volcengine.com/loadbalancer-protocol: https
    alb.ingress.kubernetes.io/certificate-ids: cert-04cc9e57f1b34a4ca9a0c834b2d3784b
spec:
  ingressClassName: chek-staging-alb
  rules:
    - host: app-staging.chekkk.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-app
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-app-http
  namespace: app-staging
  annotations:
    ingress.vke.volcengine.com/address-type: internet
    ingress.vke.volcengine.com/target-type: instance
    ingress.vke.volcengine.com/backend-protocol: HTTP
    ingress.vke.volcengine.com/alb-instance-id: alb-bdccywbfh0xs8dv40ord8u4k
    ingress.vke.volcengine.com/health-check-host: app-staging.chekkk.com
    ingress.vke.volcengine.com/health-check-path: /
    ingress.vke.volcengine.com/success-codes: "200,301,302"
    ingress.vke.volcengine.com/loadbalancer-port: "80"
    ingress.vke.volcengine.com/loadbalancer-protocol: http
spec:
  ingressClassName: chek-staging-alb
  rules:
    - host: app-staging.chekkk.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-app-http-redirect
                port:
                  number: 80

