apiVersion: v1
kind: Service
metadata:
  name: frontend-app
  namespace: app-staging
  labels:
    app.kubernetes.io/name: frontend-app
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: frontend-app
  ports:
    - name: http
      port: 80
      targetPort: 3000
      nodePort: 32434


