apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../http-redirect.staging.yaml
  - ../../ssl-redirect.staging.yaml
  - ../../api-gateway-staging.http-redirect.yaml
  - ../../api-gateway-staging.https-biz.yaml
namespace: platform-staging


