image:
  repository: chek-images-cn-beijing.cr.volces.com/saas/frontend-saas
  tag: sha-PLACEHOLDER
imagePullSecrets:
  - name: vecr-auth
service:
  port: 80
  targetPort: 3001
  name: http
ingress:
  enabled: true
  className: chek-staging-alb
  host: www-staging.chekkk.com
  tlsSecret: frontend-saas-staging-tls
  annotations:
    acme.cert-manager.io/http01-edit-in-place: "true"
ingressHttps:
  enabled: true
certificate:
  enabled: true
  issuerRefName: letsencrypt-http
  issuerRefKind: ClusterIssuer
  dnsNames:
    - www-staging.chekkk.com
env:
  USER_API_BASE: "https://www-staging.chekkk.com/api/user"
resources:
  requests: { cpu: 100m, memory: 256Mi }
  limits: { cpu: 500m, memory: 512Mi }
