image:
  repository: chek-images-cn-beijing.cr.volces.com/saas/frontend-saas
  tag: sha-PLACEHOLDER
imagePullSecrets:
  - name: vecr-auth
service:
  port: 80
  targetPort: 80
  name: http
ingress:
  enabled: true
  className: chek-prod-alb
  host: www.chekkk.com
  tlsSecret: frontend-saas-prod-tls
  annotations:
    ingress.vke.volcengine.com/address-type: internet
    ingress.vke.volcengine.com/target-type: instance
    ingress.vke.volcengine.com/backend-protocol: HTTP
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/certificate-ids: cert-04cc9e57f1b34a4ca9a0c834b2d3784b
ingressHttps:
  enabled: false
certificate:
  enabled: false
env:
  USER_API_BASE: "https://www.chekkk.com/api/user"
resources:
  requests: { cpu: 100m, memory: 256Mi }
  limits: { cpu: 500m, memory: 512Mi }
