controller:
  ingressClassResource:
    name: nginx
    controllerValue: k8s.io/ingress-nginx
  admissionWebhooks:
    enabled: true
    failurePolicy: Fail
  service:
    type: LoadBalancer
  image:
    registry: chek-images-cn-beijing.cr.volces.com
    image: devops/ingress-nginx-controller
    tag: v1.10.1
  extraArgs:
    enable-ssl-passthrough: ""
  config:
    proxy-body-size: "8m"








