apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-gateway-saas-dev
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: backend-gateway-saas=chek-images-cn-beijing.cr.volces.com/dev/backend-gateway-saas
    argocd-image-updater.argoproj.io/backend-gateway-saas.allow-tags: sha-*
    argocd-image-updater.argoproj.io/backend-gateway-saas.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: helm
    argocd-image-updater.argoproj.io/helm.image-name: image.repository
    argocd-image-updater.argoproj.io/helm.image-tag: image.tag
spec:
  project: default
  source:
    repoURL: https://github.com/chekdata/backend-gateway-saas.git
    targetRevision: main
    path: charts/backend-gateway-saas
    helm:
      releaseName: backend-gateway-saas
      parameters:
        - name: image.registry
          value: chek-images-cn-beijing.cr.volces.com
        - name: image.repository
          value: dev/backend-gateway-saas
        - name: image.tag
          value: sha-2f6552d
        - name: service.type
          value: NodePort
        - name: service.port
          value: "80"
        - name: service.targetPort
          value: "12000"
        - name: containerPort
          value: "12000"
        - name: env.NACOS_HOST
          value: "172.31.120.5"
        - name: env.NACOS_PORT
          value: "8848"
        - name: env.SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR
          value: "172.31.120.5:8848"
        - name: env.SPRING_CLOUD_NACOS_DISCOVERY_NAMESPACE
          value: "a15810b5-cca6-4eb2-9f6d-7a2c0d68fa76"
        - name: env.SPRING_CLOUD_NACOS_DISCOVERY_ENABLED
          value: "true"
        - name: env.SPRING_CLOUD_NACOS_DISCOVERY_REGISTER_ENABLED
          value: "false"
        - name: env.SPRING_CLOUD_NACOS_DISCOVERY_USERNAME
          value: "nacos"
        - name: env.SPRING_CLOUD_NACOS_DISCOVERY_PASSWORD
          value: "tnM*fb6P"
        - name: env.SPRING_AUTOCONFIGURE_EXCLUDE
          value: "org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure,org.mybatis.spring.boot.autoconfigure.MybatisAutoConfiguration,org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration"
        - name: env.MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED
          value: "true"
        - name: env.MANAGEMENT_HEALTH_DB_ENABLED
          value: "false"
        - name: env.MANAGEMENT_HEALTH_REDIS_ENABLED
          value: "false"
        - name: env.SPRING_PROFILES_ACTIVE
          value: "no-db"
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

