apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-saas-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ssh://git@ssh.github.com:443/chekdata/ops-bootstrap.git
    targetRevision: main
    path: templates/helm/examples/frontend-saas/charts/frontend-saas
    helm:
      valueFiles:
        - values.prod.yaml
      parameters:
        - name: ingress.className
          value: chek-prod-alb
  destination:
    server: https://kubernetes.default.svc
    namespace: frontend-saas-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true



