apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vehicle-model-service-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/chekdata/vehicle-model-service.git
    targetRevision: main
    path: helm/vehicle-model-service
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: miker-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true


