apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yapi-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ssh://git@ssh.github.com:443/chekdata/ops-bootstrap.git
    targetRevision: main
    path: platform/yapi-prod
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true



