apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway-staging-https-biz
  namespace: platform-staging
  annotations:
    alb.ingress.kubernetes.io/certificate-ids: cert-04cc9e57f1b34a4ca9a0c834b2d3784b
    alb.ingress.kubernetes.io/group.name: chek-staging-alb
    alb.ingress.kubernetes.io/group.order: "1"
    alb.ingress.kubernetes.io/healthcheck-host: api-staging.chekkk.com
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "10"
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "3"
    alb.ingress.kubernetes.io/healthy-threshold-count: "3"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=120
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/success-codes: "200"
    alb.ingress.kubernetes.io/target-type: instance
    ingress.vke.volcengine.com/address-type: internet
    ingress.vke.volcengine.com/alb-instance-name: chek-staging-alb
    ingress.vke.volcengine.com/backend-protocol: HTTP
    ingress.vke.volcengine.com/loadbalancer-port: "443"
    ingress.vke.volcengine.com/loadbalancer-protocol: https
    ingress.vke.volcengine.com/target-type: instance
spec:
  ingressClassName: chek-staging-alb
  rules:
  - host: api-staging.chekkk.com
    http:
      paths:
      - path: /api/auth/
        pathType: Prefix
        backend:
          service:
            name: backend-gateway-saas
            port:
              number: 80
      - path: /api/backend-app/
        pathType: Prefix
        backend:
          service:
            name: backend-gateway-saas
            port:
              number: 80
      - path: /api/backend-saas/
        pathType: Prefix
        backend:
          service:
            name: backend-gateway-saas
            port:
              number: 80
      - path: /api/offline/
        pathType: Prefix
        backend:
          service:
            name: backend-gateway-saas
            port:
              number: 80
      - path: /api/vms/
        pathType: Prefix
        backend:
          service:
            name: backend-gateway-saas
            port:
              number: 80
      - path: /api/osmgw/
        pathType: Prefix
        backend:
          service:
            name: backend-gateway-saas
            port:
              number: 80
      - path: /api/osm-gateway/
        pathType: Prefix
        backend:
          service:
            name: backend-gateway-saas
            port:
              number: 80


