apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway-dev-http
  namespace: platform-dev
  annotations:
    alb.ingress.kubernetes.io/group.name: chek-dev-alb
    alb.ingress.kubernetes.io/group.order: '0'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    ingress.vke.volcengine.com/address-type: internet
    ingress.vke.volcengine.com/target-type: instance
    ingress.vke.volcengine.com/backend-protocol: HTTP
    ingress.vke.volcengine.com/actions.ssl-redirect: '{"Type":"redirect","RedirectConfig":{"Protocol":"HTTPS","Port":"443","StatusCode":"HTTP_301"}}'
spec:
  ingressClassName: chek-dev-alb
  rules:
  - host: api-dev.chekkk.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ssl-redirect
            port:
              number: 80


