apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway-openapi-osm
  namespace: platform-prod
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-ids: cert-04cc9e57f1b34a4ca9a0c834b2d3784b
    ingress.vke.volcengine.com/address-type: internet
    ingress.vke.volcengine.com/target-type: instance
    ingress.vke.volcengine.com/backend-protocol: HTTP
    alb.ingress.kubernetes.io/target-type: instance
    ingress.vke.volcengine.com/alb-instance-name: chek-prod-alb
spec:
  ingressClassName: chek-prod-alb
  rules:
  - host: api.chekkk.com
    http:
      paths:
      - path: /api/osm-gateway/healthz
        pathType: Exact
        backend:
          service:
            name: osm-gateway
            port:
              number: 80
      - path: /api/osm-gateway/openapi.json
        pathType: Exact
        backend:
          service:
            name: osm-gateway
            port:
              number: 80
