apiVersion: v1
kind: ServiceAccount
metadata:
  name: vehicle-model-service-tos
  namespace: miker-prod
  annotations:
    # Replace with VKE OIDC role annotation key if different
    eks.amazonaws.com/role-arn: arn:volcengine:iam::1234567890:role/vehicle-model-service-tos-prod





