{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) .Values.persistence.storageClass }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: <service>-pvc
  namespace: <namespace>
spec:
  accessModes: [ "ReadWriteMany" ]
  storageClassName: {{ .Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}


