apiVersion: v1
kind: Service
metadata:
  name: <service>
  namespace: <namespace>
  labels:
    app.kubernetes.io/name: <service>
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: <service>
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default .Values.containerPort }}
      protocol: TCP

