apiVersion: v1
kind: Service
metadata:
  name: <service>
  namespace: <namespace>
  labels:
    app.kubernetes.io/name: <service>
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: <service>
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP

