replicaCount: 1

image:
  registry: chek-images-cn-beijing.cr.volces.com
  repository: <imageRepo>/<service>
  tag: "sha-<short>"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: vecr-auth

containerPort: 3000

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

# key-value env map, rendered as container env vars
env: {}

# optional secret name; if set, will be attached via envFrom.secretRef
envFromSecret: ""
# optional extra secrets; if set, each name will be attached via envFrom.secretRef
envFromSecrets: []

persistence:
  enabled: false
  # Use existing PVC name (preferred) OR set storageClass & size to create one
  existingClaim: ""
  storageClass: ""
  size: 50Gi
  # List of mounts. Each item: { name, mountPath, subPath(optional) }
  mounts: []

ingress:
  enabled: false
  host: ""
  tlsSecret: ""

