apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../http-redirect.dev.yaml
  - ../../ssl-redirect.dev.yaml
  - ../../api-gateway-dev.http-redirect.yaml
  - ../../api-gateway-dev.https-biz.yaml
namespace: platform-dev


