apiVersion: v1
kind: Service
metadata:
  name: ssl-redirect
  namespace: miker-staging
  labels:
    app: ssl-redirect
spec:
  type: ClusterIP
  ports:
    - name: use-annotation
      port: 80
      targetPort: 80
      protocol: TCP


