apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../api-gateway.prod.yaml
  - ../../http-redirect.miker-prod.yaml
  - ../../api-gateway.openapi-osm.prod.yaml
namespace: miker-prod

