apiVersion: v1
kind: Service
metadata:
  name: frontend-saas-nodeport
  namespace: frontend-saas-staging
  labels:
    app.kubernetes.io/name: frontend-saas
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: frontend-saas
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP

