name: build-kaniko

on:
  push:
    branches: [ main ]
    paths:
      - 'tools/kaniko/**'
      - '.github/workflows/build-kaniko.yml'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_ENDPOINT }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Enable Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: tools/kaniko
          push: true
          tags: |
            ${{ secrets.REGISTRY_ENDPOINT }}/devops/kaniko:latest
            ${{ secrets.REGISTRY_ENDPOINT }}/devops/kaniko:v1.23.0





