apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-app-ingress-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ssh://git@ssh.github.com:443/chekdata/ops-bootstrap.git
    targetRevision: main
    path: frontend-app-staging
  destination:
    server: https://kubernetes.default.svc
    namespace: app-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true

